name: Sync Upstream Release

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Get latest upstream release tag
        id: get_upstream_tag
        run: |
          LATEST_TAG=$(curl -sL -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/XIU2/CloudflareSpeedTest/releases/latest" | jq -r .tag_name)
          echo "tag=${LATEST_TAG}" >> $GITHUB_OUTPUT
        
      - name: Get latest mirror release tag
        id: get_mirror_tag
        run: |
          LATEST_TAG=$(curl -sL -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/${{ github.repository }}/releases/latest" | jq -r .tag_name || echo "tag=null")
          echo "tag=${LATEST_TAG}" >> $GITHUB_OUTPUT

      - name: Download specific architecture assets
        id: download
        if: steps.get_upstream_tag.outputs.tag != steps.get_mirror_tag.outputs.tag
        run: |
          UPSTREAM_TAG=${{ steps.get_upstream_tag.outputs.tag }}
          echo "New version found: ${UPSTREAM_TAG}. Proceeding to download specific assets."
          
          API_URL="https://api.github.com/repos/XIU2/CloudflareSpeedTest/releases/tags/${UPSTREAM_TAG}"
          
          declare -a ASSET_NAMES=("cfst_linux_amd64.tar.gz" "cfst_linux_arm64.tar.gz")

          echo "Fetching asset list from ${API_URL}"
          ASSETS_JSON=$(curl -sL -H "Accept: application/vnd.github.v3+json" "${API_URL}" | jq -r '.assets')

          for name in "${ASSET_NAMES[@]}"; do
            url=$(echo "${ASSETS_JSON}" | jq -r ".[] | select(.name == \"${name}\") | .browser_download_url")
            if [ -n "$url" ]; then
              echo "-> Downloading ${name} from ${url}"
              wget -q --show-progress --progress=bar:force:noscroll --no-check-certificate "${url}"
            else
              echo "Warning: Asset ${name} not found in release ${UPSTREAM_TAG}."
            fi
          done

      - name: Create new release and upload assets
        if: steps.download.conclusion == 'success'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_upstream_tag.outputs.tag }}
          files: "*.tar.gz"
